package com.miguelcr.callphonedatabase.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CALL_PHONE".
 */
@Entity
public class CallPhone {

    @Id(autoincrement = true)
    private Long id;
    private String contactName;
    private String time;
    private Integer callType;
    private String phoneNumber;

    @Generated
    public CallPhone() {
    }

    public CallPhone(Long id) {
        this.id = id;
    }

    @Generated
    public CallPhone(Long id, String contactName, String time, Integer callType, String phoneNumber) {
        this.id = id;
        this.contactName = contactName;
        this.time = time;
        this.callType = callType;
        this.phoneNumber = phoneNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getCallType() {
        return callType;
    }

    public void setCallType(Integer callType) {
        this.callType = callType;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

}
