package com.miguelcr.callphonedatabase.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.miguelcr.callphonedatabase.db.CallPhone;

import com.miguelcr.callphonedatabase.db.CallPhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig callPhoneDaoConfig;

    private final CallPhoneDao callPhoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        callPhoneDaoConfig = daoConfigMap.get(CallPhoneDao.class).clone();
        callPhoneDaoConfig.initIdentityScope(type);

        callPhoneDao = new CallPhoneDao(callPhoneDaoConfig, this);

        registerDao(CallPhone.class, callPhoneDao);
    }
    
    public void clear() {
        callPhoneDaoConfig.clearIdentityScope();
    }

    public CallPhoneDao getCallPhoneDao() {
        return callPhoneDao;
    }

}
